[features]
seeds = false

[programs.localnet]
poseidon = "7fkznAWPGcMC1ck9Y1c16gMh8wqf1J4NgyJ9NFzGfRaV"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"